
name: Node.js CI

on:
  push:
    branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: CI=false npm run build
    
    - name: stop nginx
    - run: |
        chmod +x ./aws/scripts/application-stop.sh
      shell: bash  

    - name: before install new code
    - run: |
        chmod +x ./aws/scripts/before-install.sh
      shell: bash  

    - name: after install
    - run: |
        chmod +x ./aws/scripts/after-install.sh
      shell: bash 

    - name: after install
    - run: |
        chmod +x ./aws/scripts/after-install.sh
      shell: bash 
 
